---
apiVersion: cluster.x-k8s.io/v1beta2
kind: ClusterClass
metadata:
  name: proxmox-clusterclass-cilium-v0.1.0
spec:
  controlPlane:
    healthCheck:
      checks:
        nodeStartupTimeoutSeconds: 900
        unhealthyNodeConditions:
        - status: Unknown
          timeoutSeconds: 300
          type: Ready
        - status: "False"
          timeoutSeconds: 300
          type: Ready
    machineInfrastructure:
      templateRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: ProxmoxMachineTemplate
        name: proxmox-clusterclass-v0.1.0-control-plane-template
    naming:
      template: '{{ .cluster.name }}-control-plane-{{ .random }}'
    templateRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: KubeadmControlPlaneTemplate
      name: proxmox-kubernetes-engine
  infrastructure:
    templateRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
      kind: ProxmoxClusterTemplate
      name: proxmox-clusterclass-cilium-v0.1.0-clustertemplate
  workers:
    machineDeployments:
    - bootstrap:
        templateRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
          kind: KubeadmConfigTemplate
          name: proxmox-kubernetes-engine-workertemplate
      class: proxmox-worker
      healthCheck:
        checks:
          nodeStartupTimeoutSeconds: 900
          unhealthyNodeConditions:
          - status: Unknown
            timeoutSeconds: 300
            type: Ready
          - status: "False"
            timeoutSeconds: 300
            type: Ready
        remediation:
          triggerIf:
            unhealthyLessThanOrEqualTo: 33%
      infrastructure:
        templateRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
          kind: ProxmoxMachineTemplate
          name: proxmox-clusterclass-v0.1.0-workertemplate
      metadata:
        labels:
          node-role.kubernetes.io/node: ""
          topology.kubernetes.io/region: Datacenter
      naming:
        template: '{{ .cluster.name }}-worker-{{ .random }}'
  variables: []
  patches: []