- op: add
  path: /spec/patches/-
  value:
    name: ControlPlaneDefaultNetwork
    description: "Configure ControlPlane Network Adapters"
    enabledIf: "{{ if .cloneSpec.machineSpec.controlPlane.network }}true{{ end }}"
    definitions:
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: ProxmoxMachineTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: add
            path: /spec/template/spec/network
            valueFrom:
              variable: cloneSpec.machineSpec.controlPlane.network