- op: add
  path: /spec/patches/-
  value:
    name: ControlPlaneCores
    description: "Configure Control Plane Cores"
    enabledIf: "{{ if .cloneSpec.machineSpec.controlPlane.numCores }}true{{ end }}"
    definitions:
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: ProxmoxMachineTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: add
            path: /spec/template/spec/numCores
            valueFrom:
              variable: cloneSpec.machineSpec.controlPlane.numCores