- op: add
  path: /spec/patches/-
  value:
    name: ControlPlaneMem
    description: "Configure ControlPlane Memory"
    enabledIf: "{{ if .cloneSpec.machineSpec.workerNode.memoryMiB }}true{{ end }}"
    definitions:
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: ProxmoxMachineTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: add
            path: /spec/template/spec/memoryMiB
            valueFrom:
              variable: cloneSpec.machineSpec.controlPlane.memoryMiB