- op: add
  path: /spec/patches/-
  value:
    name: NodeVmIDRange
    description: "Configure VM ID Range for all ProoxmoxMachineTemplates"
    enabledIf: "{{ if .cloneSpec.vmIDRange }}true{{ end }}"
    definitions:
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
          kind: ProxmoxMachineTemplate
          matchResources:
            controlPlane: true
            machineDeploymentClass:
              names:
              - proxmox-worker
        jsonPatches:
          - op: add 
            path: /spec/template/spec/vmIDRange 
            valueFrom:
              template: |
                {{ toJson .cloneSpec.vmIDRange }}