- op: add
  path: /spec/patches/-
  value:
    name: WorkerNodeBootDisk
    description: "Configure WorkerNode boot disk device & size"
    enabledIf: "{{ if .cloneSpec.machineSpec.workerNode.disks.bootVolume.sizeGb }}true{{ end }}"
    definitions:
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1  
          kind: ProxmoxMachineTemplate
          matchResources:
            controlPlane: false
            machineDeploymentClass:
              names:
                - proxmox-worker
        jsonPatches:
          - op: add
            path: /spec/template/spec/disks/bootVolume/disk
            valueFrom:
              variable: cloneSpec.machineSpec.workerNode.disks.bootVolume.disk
          - op: add
            path: /spec/template/spec/disks/bootVolume/sizeGb
            valueFrom:
              variable: cloneSpec.machineSpec.workerNode.disks.bootVolume.sizeGb
