apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium-ipv6-dual-stack
spec:
  clusterSelector:
    matchLabels:
      caprox.eu/cni: cilium-ipv6-dual-stack
  releaseName: cilium
  version: 1.19.3
  repoURL: https://helm.cilium.io/
  chartName: cilium
  namespace: kube-system
  valuesTemplate: |
    ipv6:
     enabled: true