- op: add
  path: /spec/patches/-
  value:
    name: ControlPlaneSetup
    description: "How to bind the Control Plane and what K8S version"
    definitions:
      - selector:
          apiVersion: controlplane.cluster.x-k8s.io/v1beta1
          kind: KubeadmControlPlaneTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: add
            path: /spec/template/spec/kubeadmConfigSpec/users
            valueFrom:
              template: |
                - name: root
                  sshAuthorizedKeys: {{ .cloneSpec.sshAuthorizedKeys }}
          - op: add
            path: /spec/template/spec/kubeadmConfigSpec/files/-
            valueFrom:
              template: |
                owner: root:root
                path: /etc/kubernetes/manifests/kube-vip.yaml
                content: |
                  apiVersion: v1
                  kind: Pod
                  metadata:
                    creationTimestamp: null
                    name: kube-vip
                    namespace: kube-system
                  spec:
                    containers:
                    - args:
                      - manager
                      env:
                      - name: cp_enable
                        value: "true"
                      - name: vip_interface
                        value: "{{ .cloneSpec.virtualIPNetworkInterface }}"
                      - name: address
                        value: "{{ .controlPlaneEndpoint.host }}"
                      - name: port
                        value: "6443"
                      - name: vip_arp
                        value: "true"
                      - name: vip_leaderelection
                        value: "true"
                      - name: vip_leaseduration
                        value: "15"
                      - name: vip_renewdeadline
                        value: "10"
                      - name: vip_retryperiod
                        value: "2"
                      image: ghcr.io/kube-vip/kube-vip:v0.5.11
                      imagePullPolicy: IfNotPresent
                      name: kube-vip
                      resources: {}
                      securityContext:
                        capabilities:
                          add:
                          - NET_ADMIN
                          - NET_RAW
                      volumeMounts:
                      - mountPath: /etc/kubernetes/admin.conf
                        name: kubeconfig
                    hostAliases:
                    - hostnames:
                      - kubernetes
                      ip: 127.0.0.1
                    hostNetwork: true
                    volumes:
                    - hostPath:
                        path: /etc/kubernetes/admin.conf
                        type: FileOrCreate
                      name: kubeconfig
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
          kind: ProxmoxMachineTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: replace
            path: /spec/template/spec/sourceNode
            valueFrom:
              variable: cloneSpec.vmTemplate.sourceNode
          - op: replace
            path: /spec/template/spec/templateID
            valueFrom:
              variable: cloneSpec.vmTemplate.templateID