apiVersion: v1
stringData:
  proxmox-credentials: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: proxmox-credentials
      namespace: kube-system
    stringData:
      token_id: "xxx@pve!capi"
      token_secret: "xxx-xxx-xxx-xxx-xxx"
kind: Secret
metadata:
  name: proxmox-credentials
  annotations:
    docs: this is the secret which will be used in the workload cluster to attach and detach volumes
type: addons.cluster.x-k8s.io/resource-set