# configure controlPlaneEndpoint
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    # mandatory for functional cluster
    caprox.eu/cni: cilium # or "caprox.eu/cni: cilium-ipv6-dual-stack" if you have ipv6 in your network
    caprox.eu/ccm: "true"
    caprox.eu/inject-proxmox-credentials: "true"
    # optional
    caprox.eu/csi: "true"
    caprox.eu/service-lb: "true"
  name: manuels-k8s-cluster
  namespace: caprox-kubernetes-engine 
spec:
  topology:
    classRef: 
      name: proxmox-clusterclass-cilium-v0.1.0
      namespace: caprox-kubernetes-engine
    version: 1.34.7
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
      - class: proxmox-worker
        name: proxmox-worker-pool
        replicas: 1
    variables:
    - name: cloneSpec
      value:
        vmTemplate:
          templateTag: "v1-34-7"
        #Example of if you want to modify node resources
        #machineSpec:
        #  controlPlane:
        #    numCores: 2
        #    numSockets: 1
        #    memoryMiB: 4096
        #  workerNode:
        #    numCores: 6
        #    numSockets: 1
        #    memoryMiB: 6144
        #    disks:
        #      bootVolume:
        #        disk: scsi0
        #        sizeGb: 80
    - name: controlPlaneEndpoint
      value:
        host: 192.168.178.210