# app-cluster-api.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: argocd
spec:
  destination:
    namespace: capi-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    targetRevision: 0.24.0
    chart: cluster-api-operator
    helm:
      values: |
        manager:
          featureGates:
            proxmox:
              ClusterTopology: true
            core:
              ClusterTopology: true
            kubeadm:
              ClusterTopology: true
        core:
          cluster-api:
            enabled: true
            version: v1.11.3
        bootstrap:
          kubeadm: 
            enabled: true
            version: v1.11.3
        controlPlane: 
          kubeadm: 
            enabled: true
            version: v1.11.3
        infrastructure: 
          proxmox:
            enabled: true
            version: v0.7.5
        ipam:
          in-cluster:
            enabled: true
            version: v1.0.3
        addon:
          helm: 
            enabled: true
            version: v0.4.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated: 
      prune: true
      selfHeal: true