# app-proxmox-kubernetes-engine.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-kubernetes-engine
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: capi-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Caprox-eu/Proxmox-Kubernetes-Engine.git
    targetRevision: main
    path: manifests/clusterclass-cilium-with-shared-ippool/base
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: cluster.x-k8s.io
      kind: ClusterClass
      jsonPointers:
        - /spec