- op: add
  path: /spec/variables/-
  value: 
    name: ipv4Config
    required: false
    schema:
      openAPIV3Schema:
        properties:
          addresses:
            default:
            - 10.10.10.10-10.10.10.15
            items:
              type: string
            minItems: 1
            type: array
          gateway:
            default: 10.10.10.1
            type: string
          metric:
            default: 100
            type: integer
          prefix:
            default: 24
            type: integer
        type: object