- op: add
  path: /spec/variables/-
  value:  
    name: ipv6Config
    required: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          addresses:
            minItems: 1
            type: array
            items:
              type: string
          prefix:
            type: integer
            default: 64
          gateway:
            type: string