# app-cluster-api.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: capi-operator-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    targetRevision: 0.26.0
    chart: cluster-api-operator
    helm:
      values: |
        core:
          cluster-api:
            enabled: true
            version: v1.11.10
            manager:
              featureGates:
                ClusterTopology: true
        bootstrap:
          kubeadm: 
            enabled: true
            version: v1.11.10
            manager:
              featureGates:
                ClusterTopology: true
        controlPlane: 
          kubeadm: 
            enabled: true
            version: v1.11.10
            manager:
              featureGates:
                ClusterTopology: true
        infrastructure: 
          proxmox:
            enabled: true
            version: v0.8.1
            manager:
              featureGates:
                ClusterTopology: true
        ipam:
          in-cluster:
            enabled: true
            version: v1.0.3
        addon:
          helm: 
            enabled: true
            version: v0.5.3
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated: 
      prune: true
      selfHeal: true